# Generated by Django 5.2.3 on 2025-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pessoas/'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='historia_pessoal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
