# Generated by Django 4.2.4 on 2025-06-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_foto_pessoa_historia_pessoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_falecimento_incerta',
            field=models.CharField(blank=True, help_text="Ex: 'cerca de 1950', 'antes de 1990', 'final do século XX'. Preenche se a data exata for desconhecida.", max_length=100, null=True, verbose_name='Data de Falecimento (Incerta)'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='local_nascimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Nascimento'),
        ),
    ]
