# Generated by Django 4.2.4 on 2025-06-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_data_falecimento_incerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='estado_nascimento',
            field=models.CharField(blank=True, help_text='Sigla do estado (ex: SP, MG, TO). Usado para as Origens Regionais.', max_length=2, null=True, verbose_name='Estado de Nascimento (UF)'),
        ),
    ]
