# Generated by Django 4.2.4 on 2025-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoa_estado_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='relacao',
            field=models.CharField(blank=True, choices=[('Voce', 'Você'), ('Pai', 'Pai'), ('Mae', 'Mãe'), ('Filho', 'Filho(a)'), ('Irmao', 'Irmão(ã)'), ('Conjuge', 'Cônjuge'), ('Avo', 'Avô(ó)'), ('Neto', 'Neto(a)'), ('Tio', 'Tio(a)'), ('Sobrinho', 'Sobrinho(a)'), ('Primo', 'Primo(a)'), ('Padrasto', 'Padrasto'), ('Madrasta', 'Madrasta'), ('Enteado', 'Enteado(a)'), ('Cunhado', 'Cunhado(a)'), ('Genro', 'Genro'), ('Nora', 'Nora'), ('Companheiro', 'Companheiro(a)'), ('Bisavo', 'Bisavô(ó)'), ('Bisneto', 'Bisneto(a)'), ('Avoengos', 'Avoengos (Pais dos bisavós)'), ('DescendenteDireto', 'Descendente Direto (Ex: trineto)'), ('AscendenteDireto', 'Ascendente Direto (Ex: trisavô)'), ('Primo2Grau', 'Primo de Segundo Grau'), ('Sogro', 'Sogro(a)'), ('TioAfinidade', 'Tio(a) por Afinidade'), ('Outro', 'Outro'), ('Desconhecido', 'Desconhecido')], help_text='Defina o parentesco primário desta pessoa, se aplicável.', max_length=50, null=True, verbose_name='Parentesco Principal'),
        ),
    ]
