# Generated by Django 4.2.4 on 2025-06-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_pessoa_relacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='conjuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuges', to='pessoas.pessoa', verbose_name='Cônjuge'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='relacao',
            field=models.CharField(blank=True, choices=[('Voce', 'Você'), ('Pai', 'Pai'), ('Mae', 'Mãe'), ('Filho', 'Filho(a)'), ('Irmao', 'Irmão(ã)'), ('Conjuge', 'Cônjuge'), ('Avo', 'Avô(ó)'), ('Neto', 'Neto(a)'), ('Tio', 'Tio(a)'), ('Sobrinho', 'Sobrinho(a)'), ('Primo1Grau', 'Primo(a) de Primeiro Grau'), ('Padrasto', 'Padrasto'), ('Madrasta', 'Madrasta'), ('Enteado', 'Enteado(a)'), ('Cunhado', 'Cunhado(a)'), ('Genro', 'Genro'), ('Nora', 'Nora'), ('Companheiro', 'Companheiro(a)'), ('Bisavo', 'Bisavô(ó)'), ('Bisneto', 'Bisneto(a)'), ('Avoengos', 'Avoengos (Pais dos bisavós)'), ('Tataravo', 'Tataravô(ó)'), ('Tatarateto', 'Tatarane(ta/to)'), ('Primo2Grau', 'Primo(a) de Segundo Grau'), ('Primo3Grau', 'Primo(a) de Terceiro Grau'), ('TioAvo', 'Tio(a)-Avô(ó)'), ('SobrinhoNeto', 'Sobrinho(a)-Neto(a)'), ('Sogro', 'Sogro(a)'), ('NoraGenro', 'Nora/Genro'), ('TioAfinidade', 'Tio(a) por Afinidade'), ('IrmaoAfinidade', 'Irmão(ã) por Afinidade (Cunhado)'), ('PrimoAfinidade', 'Primo(a) por Afinidade'), ('Outro', 'Outro'), ('Desconhecido', 'Desconhecido')], help_text='Defina o parentesco primário desta pessoa, se aplicável.', max_length=50, null=True, verbose_name='Parentesco Principal'),
        ),
    ]
