# Generated by Django 4.2.4 on 2025-06-19 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0006_alter_pessoa_options_pessoa_conjuge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='owner',
            field=models.ForeignKey(default=1, help_text='O usuário que gerencia/criou esta pessoa na árvore.', on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_proprietarias', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associa esta pessoa a um usuário do sistema para login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa_associada', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Associado (opcional)'),
        ),
    ]
