# Generated by Django 4.2.4 on 2025-06-20 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_pessoa_owner_pessoa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='relacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='conjuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuges_historicos', to='pessoas.pessoa', verbose_name='Cônjuge Principal'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_falecimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Falecimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pessoas/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='historia_pessoal',
            field=models.TextField(blank=True, null=True, verbose_name='História Pessoal'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_da_mae', to='pessoas.pessoa', verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_do_pai', to='pessoas.pessoa', verbose_name='Pai'),
        ),
    ]
